apiVersion: apps/v1
kind: Deployment
metadata:
  name: delpoy-express-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-3
  template:
    metadata:
      labels:
        app: express-3
    spec:
      containers:
        - name: express-3
          image: userjalil/express-fazztrack-3:2.0
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
            - name: DB_HOST
              value: psql-service
          command:
            [
              "/bin/sh",
              "-c",
              "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: express-3-service
spec:
  selector:
    app: express-3
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
