version: '3'

services:
  psql-service:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: jalil
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: express_fazztrack_3

  express-3:
    image: userjalil/express-fazztrack-3:1.0
    depends_on:
      - psql-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: psql-service
    command: /bin/sh -c " npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev "
